### ISSUE TITLE
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by shrikumarhegde** [scokmen/angularjs-gulp-boilerplate#1]
Hi,
I am getting below error on prod version
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Is there any quick fix?

**Comment by scokmen** [comment]
Hi,
I have not encountered this problem before. This error can happen when the CSS file starts with comment lines. Can you check it?
https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type
